name: Run Gradle test

on:
  push:
    branches:
      - master
      - releases/*

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: "8"
        distribution: "temurin"
    - uses: gradle/gradle-build-action@v2
      name: gradle test
      with:
        arguments: test
